# Site settings
title: Elmer Lastdrager (SIDN Labs)
tag_text: Elmer Lastdrager
description: Elmer Lastdrager is a Research Engineer at SIDN Labs, specialised in phishing and IoT.

# Build settings
markdown: kramdown

exclude: ["README.md"]
