# Site settings
title: Elmer Lastdrager (University of Twente)
tag_text: Elmer Lastdrager
description: Elmer Lastdrager is a PhD student at the University of Twente specialised in Phishing.

# Build settings
markdown: kramdown

exclude: ["README.md"]
